services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fred_pipeline

  python:
    build:
      context: .
      dockerfile: data_ingestion/Dockerfile
    container_name: ingestion
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fred_pipeline

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    env_file: .env
    environment:
      - DBT_PROFILES_DIR=/dbt_project
    volumes:
      - ./dbt_project:/dbt_project
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: >
      /bin/bash -c "
      dbt run --profiles-dir /dbt_project --project-dir /dbt_project &&
      dbt test --profiles-dir /dbt_project --project-dir /dbt_project &&
      dbt snapshot --profiles-dir /dbt_project --project-dir /dbt_project &&
      dbt build --profiles-dir /dbt_project --project-dir /dbt_project"
    networks:
      - fred_pipeline

  superset:
    build: ./superset
    container_name: superset
    env_file: .env
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./superset:/app/superset_home
      - ./.env:/app/.env
    command: [ "/app/superset_home/superset_entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fred_pipeline


volumes:
  postgres_data:


networks:
  fred_pipeline:
    driver: bridge
