[project]
name = "data-ingestion"
version = "0.1.0"
description = "Pulls data from the FRED API. Loads raw data into PostgreSQL."
requires-python = ">=3.12"
dependencies = [
    "psycopg>=3.3.2",
    "requests>=2.32.5",
]
